version: '3.4'

services:

# Scheduler that produces tasks for executors
  latigo-scheduler:
    image: latigo-base
    restart: always
    container_name: latigo-scheduler
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ../volumes/latigo/scheduler:/tmp/data:Z
      - ${PWD}/scheduler_local.yaml:/app/scheduler_local.yaml
    environment:
      - LATIGO_SCHEDULER_CONFIG_FILE=${LATIGO_SCHEDULER_CONFIG_FILE}
    command: ["/app/bin/scheduler.py"]

# Executor for executing tasks from scheduler
  latigo-executor:
    image: latigo-base
    restart: always
    container_name: latigo-executor
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ${PWD}/executor_local.yaml:/app/executor_local.yaml
    environment:
      - LATIGO_EXECUTOR_CONFIG_FILE=${LATIGO_EXECUTOR_CONFIG_FILE}
    command: ["/app/bin/executor.py"]
