FROM python:3.7-stretch
RUN apt-get update && apt-get install -y debconf-utils locales
# curl apt-transport-https locales ca-certificates
RUN locale-gen en_US.UTF-8
RUN update-locale
WORKDIR /app
COPY app/requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY app/ .
COPY README.md VERSION LICENSE ./
COPY deploy/ ./deploy
RUN python setup.py install
WORKDIR /app/latigo
CMD ["/app/bin/executor.py"]


