#!/bin/bash

environment_file="/root/.profile"
supervisor_config_file="deploy/supervisord.conf"


# Persist environment variables provided by Docker to file
echo "Generated by $0 at $(date)" > "$environment_file"
chmod 600 "$environment_file"
printenv | while read line
do
    IFS='=' read -ra parts <<< "$line"
    echo "export ${parts[0]}=${parts[1]}" >> "$environment_file"
done
#echo "Using environment:"
#cat "$environment_file"

#cd deploy && alembic upgrade head
supervisord -c "$supervisor_config_file"
