scheduler:
    continuous_prediction_start_time: "08:00"
    continuous_prediction_interval: "30m"
    continuous_prediction_delay: "3h"
    azure_monitor_logging_enabled: false
    azure_monitor_instrumentation_key: <key>

task_queue:
    type: "kafka"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    security.protocol: "SASL_SSL"
    ssl.ca.location: "/etc/ssl/certs/ca-certificates.crt"
    sasl.mechanism: "PLAIN"
    group.id: "1"
    client.id: "latigo_scheduler"
    request.timeout.ms: 10000
    session.timeout.ms: 10000
    default.topic.config: {"auto.offset.reset": "earliest"}
    debug: "fetch"
    topic: "latigo_topic"
    enable.auto.commit: true
    auto.commit.interval.ms: 1000
    max.poll.interval.ms: 86400000


model_info:
    type: "gordo"
    connection_string: "DO NOT PUT SECRETS IN THIS FILE"
    metadata: null
    batch_size: 1000
    parallelism: 10
    forward_resampled_sensors : false
    n_retries: 5
    use_parquet: true
    data_provider:
        debug: true
        n_retries: 5
    prediction_forwarder:
        debug: false
        n_retries: 5
    auth:
        resource: "set from env"
        tenant: "set from env"
        authority_host_url: "set from env"
        client_id: "set from env"
        client_secret: "DO NOT PUT SECRETS IN THIS FILE"

models_metadata_info:
    type: "metadata_api"
    base_url: "REPLACE"
    auth:
        resource: "REPLACE"
        tenant: "REPLACE"
        authority_host_url: "REPLACE"
        client_id: "REPLACE"
        client_secret: "REPLACE"
        auto_adding_headers:
            Ocp-Apim-Subscription-Key: "REPLACE"